### ISSUE TITLE
Can't use async / await functions

### ISSUE THREAD

**Issue by marceautassin** [lewagon/webpack-boilerplate#8]
Boilerplate setup can't handle javascript `async / await` functions.

Example:
```javascript
const fetchApi = async () => {
  const response = await fetch("http://www.omdbapi.com/?s=harry potter&apikey=adf1f2d7");
  const data = await response.json();
  console.log(data);
};

fetchApi();
```

To fix that issue:
1. Add `"@babel/plugin-transform-runtime": "^7.17.10"` in `package.json` dependencies.
2. Add `"@babel/plugin-transform-runtime"` in `babelrc` file `plugins` section.

**Comment by dmilon** [comment]
Hi @marceautassin :wave: Thank you for your report and your suggestion :pray: I've added the plugin :heavy_check_mark:
